[project]
name = "forecasting-app-fashhtml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pre-commit>=3.8.0",
    "python-fasthtml>=0.6.4",
]
